/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package From;

import DoiTuong.GradeOB;
import DoiTuong.SinhVienOB;
import ListOB.Grade;
import ListOB.SinhVien;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenMinhHau_PS24488
 */
public final class quanlidiem extends javax.swing.JFrame {

    /**
     * Creates new form quanlidiem
     */
    Grade sv = new Grade();
    ArrayList<GradeOB> lsv = new ArrayList<>();

    //tao list dữ liệu mẫu
    public void addData() {
        lsv = sv.getAll();
    }

    public quanlidiem() {

        initComponents();
        setTitle("Quản lí điểm sinh viên");
        setLocationRelativeTo(this);
        addData();
        setTable();
        filltotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtms = new javax.swing.JTextField();
        txthvt = new javax.swing.JTextField();
        txttoan = new javax.swing.JTextField();
        txtli = new javax.swing.JTextField();
        txthoa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbldiem = new javax.swing.JLabel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldiem = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnleftend = new javax.swing.JButton();
        btnleft = new javax.swing.JButton();
        btnright = new javax.swing.JButton();
        btnrightend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/asm/Image/qldsv.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí điểm sinh viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Mã số sinh viên");

        txttimkiem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
        });

        btntimkiem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/search.png"))); // NOI18N
        btntimkiem.setText("Search");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntimkiem)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên sinh viên");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Mã sinh viên");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Toán");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Lí");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Hóa");

        txtms.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txthvt.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txttoan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txttoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoanActionPerformed(evt);
            }
        });
        txttoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttoanKeyPressed(evt);
            }
        });

        txtli.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtliKeyPressed(evt);
            }
        });

        txthoa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Điểm trung bình");

        lbldiem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbldiem.setForeground(new java.awt.Color(255, 0, 0));
        lbldiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txthoa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbldiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txttoan, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txthvt)
                    .addComponent(txtms))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthvt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnnew.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/new1.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/save1.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/delete.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/update1.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        tbldiem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbldiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ tên sinh viên", "Toán", "Lí", "Hóa", "Điểm TB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbldiem.setRowHeight(18);
        tbldiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldiem);
        if (tbldiem.getColumnModel().getColumnCount() > 0) {
            tbldiem.getColumnModel().getColumn(0).setMinWidth(120);
            tbldiem.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbldiem.getColumnModel().getColumn(0).setMaxWidth(120);
            tbldiem.getColumnModel().getColumn(2).setMaxWidth(100);
            tbldiem.getColumnModel().getColumn(3).setMaxWidth(100);
            tbldiem.getColumnModel().getColumn(4).setMaxWidth(100);
            tbldiem.getColumnModel().getColumn(5).setMinWidth(130);
            tbldiem.getColumnModel().getColumn(5).setMaxWidth(130);
        }

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Top 3 sinh viên có điểm trung bình cao nhất");

        btnleftend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/leftend.png"))); // NOI18N
        btnleftend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftendActionPerformed(evt);
            }
        });

        btnleft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/lefy1.png"))); // NOI18N
        btnleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftActionPerformed(evt);
            }
        });

        btnright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/right1.png"))); // NOI18N
        btnright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightActionPerformed(evt);
            }
        });

        btnrightend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm/Image/rightend.png"))); // NOI18N
        btnrightend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnleftend, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnleft, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnright, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnrightend, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnew)
                        .addGap(51, 51, 51)
                        .addComponent(btnsave)
                        .addGap(51, 51, 51)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndelete))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnleftend)
                    .addComponent(btnleft)
                    .addComponent(btnright)
                    .addComponent(btnrightend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            create();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txttoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoanActionPerformed

    private void btnrightendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightendActionPerformed
        // TODO add your handling code here:

        try {
            endright();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnrightendActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed

        if (findbyID(txttimkiem.getText()) > -1) {
            showdetail(findbyID(txttimkiem.getText()));
        } else if (find(txttimkiem.getText())) {
            txttoan.setText("");
            txthoa.setText("");
            txtli.setText("");
            lbldiem.setText("");
            tbldiem.clearSelection();
        } else {
            JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightActionPerformed

        try {
            right();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnrightActionPerformed

    private void btnleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftActionPerformed
        // TODO add your handling code here:
        try {
            left();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnleftActionPerformed

    private void btnleftendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftendActionPerformed
        // TODO add your handling code here
        try {
            endleft();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnleftendActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        txttimkiem.setText("");
        txtms.setText("");
        txthvt.setText("");
        txttoan.setText("");
        txthoa.setText("");
        txtli.setText("");
        lbldiem.setText("");
        tbldiem.clearSelection();
    }//GEN-LAST:event_btnnewActionPerformed

    private void tbldiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldiemMouseClicked
        int index = tbldiem.getSelectedRow();
        showdetail(index);
    }//GEN-LAST:event_tbldiemMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
            delete();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            update();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txttoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttoanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtli.requestFocus();
        }
    }//GEN-LAST:event_txttoanKeyPressed

    private void txtliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            txthoa.requestFocus();
    }//GEN-LAST:event_txtliKeyPressed

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (findbyID(txttimkiem.getText()) > -1) {
                showdetail(findbyID(txttimkiem.getText()));
            } else if (find(txttimkiem.getText())) {
                txttoan.setText("");
                txthoa.setText("");
                txtli.setText("");
                lbldiem.setText("");
                tbldiem.clearSelection();
            } else {
                JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
            }
        }
    }//GEN-LAST:event_txttimkiemKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlidiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlidiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlidiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlidiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlidiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnleft;
    private javax.swing.JButton btnleftend;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnright;
    private javax.swing.JButton btnrightend;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldiem;
    private javax.swing.JTable tbldiem;
    private javax.swing.JTextField txthoa;
    private javax.swing.JTextField txthvt;
    private javax.swing.JTextField txtli;
    private javax.swing.JTextField txtms;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttoan;
    // End of variables declaration//GEN-END:variables
public void setTable() {
        tbldiem.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 15));
        txtms.setRequestFocusEnabled(false);
        txthvt.setRequestFocusEnabled(false);
//        DefaultTableModel tablemodel = new DefaultTableModel() {
//
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//            }
//        };
//        tbldiem.setModel(tablemodel);
    }

    public int findbyID(String ID) {
        for (GradeOB OB : lsv) {
            if (OB.getMasv().equalsIgnoreCase(ID) && lsv.indexOf(OB) < 3) {
                tbldiem.setRowSelectionInterval(lsv.indexOf(OB), lsv.indexOf(OB));
                return lsv.indexOf(OB);
            } else if (OB.getMasv().equalsIgnoreCase(ID) && lsv.indexOf(OB) >= 3) {
                tbldiem.clearSelection();
                return lsv.indexOf(OB);
            }
        }

        return -1;
    }

    public int findbyID1(String ID) {
        for (GradeOB OB : lsv) {
            if (OB.getMasv().equalsIgnoreCase(ID)) {
                return lsv.indexOf(OB);
            }
        }
        return -1;
    }

    public void findbyIndex(int index) {
        if (index > -1 && index < lsv.size()) {
            tbldiem.setRowSelectionInterval(index, index);
        }

    }

    public boolean find(String ID) {
        SinhVien sv = new SinhVien();
        ArrayList<SinhVienOB> s = sv.getAll();
        for (SinhVienOB sinhVienOB : s) {
            if (sinhVienOB.getMasv().equalsIgnoreCase(ID)) {
                txtms.setText(sinhVienOB.getMasv());
                txthvt.setText(sinhVienOB.getHovaten());
                return true;
            }
        }
        return false;

    }

    public void showdetail(int index) {
        GradeOB sv = lsv.get(index);
        try {
            txtms.setText(sv.getMasv());
            txthvt.setText(sv.getHovaten());
            txttoan.setText(String.valueOf(sv.getToan()));
            txtli.setText(String.valueOf(sv.getLi()));
            txthoa.setText(String.valueOf(sv.getHoa()));
            lbldiem.setText(String.valueOf(sv.getTb()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Danh sách bị lỗi");
        }
    }

    public void left() {
        String ID = txtms.getText();
        int index = findbyID1(ID) - 1;
        if (index < 0) {
            index = lsv.size() - 1;
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        } else {
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        }
    }

    public void endleft() {
        String ID = txtms.getText();
        int index = findbyID1(ID);
        if (index != 0) {
            index = 0;
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến đầu danh sách", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void right() {
        String ID = txtms.getText();
        int index = findbyID1(ID) + 1;
        if (index > lsv.size() - 1) {
            index = 0;
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        } else {
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        }
    }

    public void endright() {
        String ID = txtms.getText();
        int index = findbyID1(ID);
        if (index != lsv.size() - 1) {
            index = lsv.size() - 1;
            showdetail(index);
            if (index < 3) {
                findbyIndex(index);
            } else if (index >= 3) {
                tbldiem.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến cuối danh sách", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void filltotable() {
        DefaultTableModel model = (DefaultTableModel) tbldiem.getModel();
        addData();
        sv.sapxep(lsv);
        model.setRowCount(0);
        for (int i = 0; i < (lsv.size() < 3 ? lsv.size() : 3); i++) {
            Object[] rowdata = {lsv.get(i).getMasv(), lsv.get(i).getHovaten(), lsv.get(i).getToan(), lsv.get(i).getLi(), lsv.get(i).getHoa(), lsv.get(i).getTb()};
            model.addRow(rowdata);
        }
    }

    public void delete() {
        if (find(txtms.getText())) {
            if (findbyID(txtms.getText()) > -1) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa điểm sinh viên này không", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/canhbao.png")));
                if (result == JOptionPane.YES_OPTION) {
                    sv.xoadiem(txtms.getText());
                    filltotable();
                    txttimkiem.setText("");
                    txtms.setText("");
                    txthvt.setText("");
                    txttoan.setText("");
                    txthoa.setText("");
                    txtli.setText("");
                    lbldiem.setText("");
                    tbldiem.clearSelection();
                    JOptionPane.showMessageDialog(this, "Xóa thành công điểm của sinh viên", "Delete", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/succes.png")));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên chưa có điểm. Không thể thực hiện thao tác.", "Delete", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên không có dữ liệu. Không thể thực hiện thao tác.", "Delete", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
        }
    }

    public void update() {
        if (find(txtms.getText())) {
            if (findbyID(txtms.getText()) > -1) {
                if (checkValidate()) {
                    double toan = Double.parseDouble(txttoan.getText());
                    double li = Double.parseDouble(txtli.getText());
                    double hoa = Double.parseDouble(txthoa.getText());
                    int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn update điểm sinh viên này không", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/canhbao.png")));
                    if (result == JOptionPane.YES_OPTION) {
                        sv.suadiem(txtms.getText(), toan, li, hoa);
                        filltotable();
                        showdetail(findbyID(txtms.getText()));
                        JOptionPane.showMessageDialog(this, "Update thành công điểm của sinh viên", "Update", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/succes.png")));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên chưa có điểm. Không thể thực hiện thao tác.", "Update", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên không có dữ liệu. Không thể thực hiện thao tác.", "Update", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
        }
    }

    public void create() {
        if (find(txtms.getText())) {
            if (findbyID(txtms.getText()) == -1) {
                if (checkValidate()) {
                    double toan = Double.parseDouble(txttoan.getText());
                    double li = Double.parseDouble(txtli.getText());
                    double hoa = Double.parseDouble(txthoa.getText());
                    int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu điểm sinh viên này không", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/canhbao.png")));
                    if (result == JOptionPane.YES_OPTION) {
                        sv.themdiem(txtms.getText(), toan, li, hoa);
                        filltotable();
                        showdetail(findbyID(txtms.getText()));
                        JOptionPane.showMessageDialog(this, "Lưu điểm của sinh viên thành công", "Save", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/succes.png")));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên này đã có điểm. Vui lòng chọn Update.", "Save", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên không có dữ liệu. Không thể thực hiện thao tác.", "Save", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/asm/Image/nosuc.png")));
        }
    }

    public boolean checkValidate() {

        try {
            double toan = Double.parseDouble(txttoan.getText());
            double li = Double.parseDouble(txtli.getText());
            double hoa = Double.parseDouble(txthoa.getText());
            if (toan <= 0 || toan > 10) {
                JOptionPane.showMessageDialog(this, "Điểm Toán trong khoảng từ 0.5 - 10", "Điểm", JOptionPane.INFORMATION_MESSAGE);
                txttoan.requestFocus();
                return false;
            }
            if (li <= 0 || li > 10) {
                JOptionPane.showMessageDialog(this, "Điểm Lí trong khoảng từ 0.5 - 10", "Điểm", JOptionPane.INFORMATION_MESSAGE);
                txtli.requestFocus();
                return false;
            }
            if (hoa <= 0 || hoa > 10) {
                JOptionPane.showMessageDialog(this, "Điểm Hóa trong khoảng từ 0.5 - 10", "Điểm", JOptionPane.INFORMATION_MESSAGE);
                txthoa.requestFocus();
                return false;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập điểm là số và dùng dấu . để phân cách phần thập phân", "ERROL", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
}
